import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import styles from "@/app/layout.module.css";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

      <header className={styles.header}>
        <div className={styles.logo}><Link href="/"><Image src={"/logo.svg"} alt={"Логотип здесь"} width={394} height={108}></Image></Link></div>
        <div className={styles.menu}>
          <ul className={styles.navbar}>
            <li><Link href="/"> ГЛАВНАЯ</Link></li>
            <li><Link href="/favourites"> ИЗБРАННОЕ</Link></li>
            
          </ul>
          <hr width='55%' size="7" color="white"></hr>
        </div>
        </header>

        {children}

        <footer className={styles.footer}>
          <h1>Подпишись!</h1>
          <Image src={"/vk.svg"} alt={"Избранное"} width={65} height={65}></Image>
          <Image src={"/instagram.svg"} alt={"Избранное"} width={65} height={65}></Image>
          <Image src={"/youtube.svg"} alt={"Избранное"} width={65} height={65}></Image>
        </footer>

      </body>
    </html>
  );
}
